# Setup
title:               Scribal
tagline:             'Revenue Growth Through Subscription Finance'
description:         'Unlocking business value through transformational technologies'
url:                 https://www.scribal.io/
baseurl:             
paginate:            5
permalink:           pretty
excerpt_separator: "<!--excerpt-->"

# About/contact
author:
  name:              Jason Horowitz
  url:               https://twitter.com/jasonhhorowitz
  email:             jason@scribal.io

# Gems
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links


# Custom vars
version:             1.2.0
google_analytics: G-ZC97505LX9

# Preserved Elements from Template
# description:         'A reserved <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
# tagline:             'A Jekyll theme'
# tagline:             'Data for Decisions | Systems for Change '
